---
title: "Zibra"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)
library(jsonlite)
library(knitr)
library(dplyr)
library(ggtree)
```

```{r ct}
samples=fromJSON('https://lims.microbesng.uk/RESTfm/ZiBRA/layout/Sample.json?RFMkey=u54PgAHTwZGTiwoLD3I8K239i8EPTSwr&RFMmax=0')$data
runsamples=fromJSON('https://lims.microbesng.uk/RESTfm/ZiBRA/layout/RunSample.json?RFMkey=u54PgAHTwZGTiwoLD3I8K239i8EPTSwr&RFMmax=0')
ggplot(samples, aes(x=as.integer(ct))) + geom_histogram() + theme_bw()
```

```{r state}
ggplot(samples, aes(x=state)) + geom_bar(stat="count") + theme_bw() + theme(axis.text.x = element_text(angle=90, hjust=1))
```

## Run statistics

```{r runstats}
runs=read.table("../../runstats.txt", header=T, sep="\t")
kable(runs, caption='Run statistics')
```

## Sequenced samples

```{r sequencedsamples}
jointable=inner_join(samples, runsamples$data, "sample_id")
sequencedsamples=unique(filter(select(jointable, sample_id, collection_date, lab, municipality, ct), sample_id!='ZBRANEG'))
kable(sequencedsamples, caption=paste('Sequenced samples: ', nrow(sequencedsamples)))
```

```{r ctsequenced}
ggplot(sequencedsamples, aes(x=as.integer(ct))) + geom_histogram()
```

## Genome statistics

```{r genomestats}
genomes=read.table("../../genomestats.txt", header=T, sep="\t")
kable(arrange(genomes, -perc), caption='Run statistics')
```

```{r covbyct}
covct=inner_join(genomes, sequencedsamples, by = c('sample' = 'sample_id'))
ggplot(subset(covct, basescovered25x > 2500), aes(x=as.numeric(ct), y=basescovered25x/10617)) + geom_point() + theme_bw() + xlab("Ct value") + ylab ("Genome coverage") + lims(y=c(0,1))
```

```{r genomestatsbyrun}
genomes=read.table("../../genomestats.txt", header=T, sep="\t")
kable(arrange(genomes, -run), caption='Run statistics')
```


### Histogram

```{r}
ggplot(genomes, aes(x=perc)) + geom_histogram(binwidth=10) + xlim(0,100) + theme_bw() + labs("Genome coverage of samples")
```

