import os
from datetime import datetime
import time

# Input directory
in_dir="/gpfs/group/andersen/gkarthik/analysis/2016.10.28.1477686704.ZF/_merged_bams"
out_dir=in_dir+"/_pileup"

SAMPLES = []
for dirname, dirnames, filenames in os.walk(in_dir):
     for f in filenames:
          if '.bam' not in f: # Specify conditions on filenames
               continue
          SAMPLES.append(f.replace(".bam", ""))

rule all:
    input:
        "{out_dir}/statistics.md".format(out_dir = out_dir)

rule get_pileup:
    input:
        "{in_dir}".format(in_dir = in_dir) + "/{sample}.bam"
    output:
        "{out_dir}/{sample}.tsv"
    shell:
        "mkdir -p $(dirname {output}) && "
        "module load samtools && "
        "samtools depth -d 1000000000 -a {input} > {output}"

rule generate_statistics:
    input:
        "{out_dir}/{sample}.tsv".format(out_dir = out_dir, sample = s) for s in SAMPLES
    output:
        "{out_dir}/statistics.md"
    shell:
        "module load python/3.5.1 && "
        "a=$(dirname {output}) &&"
        "python3 ./plot_coverage.py $a/ $a/ > {output}"
