#!/bin/bash
set -e

>&2 echo "For more documentation on the bioinformatics pipeline, see <http://zibra.readthedocs.io/en/latest/>"

schema=$1
sample=$2
directory=$3

zibra.py extract --basecaller "ONT Albacore Sequencing Software" $directory > $sample.fasta
zibra.py minion $schema $sample
